name: Notification

on:
  workflow_run:
    workflows:
      - Auto deploy
      - E2E testing
    types: [completed]
    branches: [main]

jobs:
  log-failure-event:
    name: Log event
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Send notification mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mandrillapp.com
          server_port: 465
          username: Aha-Actions-Bot
          password: ${{ secrets.MANDRILL_API_KEY }}
          subject:
            Aha system - ${{ github.event.workflow_run.name }} -
            Failed - ${{ github.event.workflow_run.head_commit.message }} - ${{ github.event.workflow_run.head_commit.message }}
          to: hieult@dgroup.co
          from: Aha-Actions-Bot <aha-actions-bot@aha.is>
          body: |
            Repository: ${{ github.repository }}
            Workflow: ${{ github.event.workflow_run.name }}
            Link: ${{ github.event.workflow_run.html_url }}
            Status: Failure
            Timestamp: ${{ github.event.workflow_run.head_commit.timestamp }}
            Commit: ${{ github.event.workflow_run.head_commit.message }} - ${{ github.event.repository.html_url }}/${{ github.event.workflow_run.head_commit.id }}
            Author: ${{ github.event.workflow_run.author.name }}
            Notify by: Github Actions
